[package]
name = "pianorium"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
piston-gfx_texture = "*"
image = "*"
gl = "*"