[package]
name = "pianorium"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = { version = "*", features = ["static"] }
egui_sdl2_gl = { version = "*", features = ["sdl2_static-link"] }
midly = "*"
num_cpus = "*"
rand = "*"