[package]
name = "pianorium"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "*"
sdl2 = { version = "*", features = ["bundled", "static-link"] }
gl = "*"
egui_sdl2_gl = "*"
midly = "*"
num_cpus = "*"