[package]
name = "pianorium"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_sdl2_gl = { version = "*", features = ["sdl2_static-link"] }
midly = "*"
num_cpus = "*"
rand = "*"
ffmpeg-next = { version = "*", features = ["static", "codec", "device", "filter", "format", "software-resampling", "software-scaling"] } 