[package]
name = "pianorium"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "*"
egui_sdl2_gl = { version = "0.16.0", features = ["sdl2_static-link"] }
midly = "*"
num_cpus = "*"
rand = "*"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"