name: Pianorium

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs: # Add caching
#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Install dependencies
#      run: |
#        cd /home
#        sudo apt-get update -y -qq && sudo apt-get -y install ffmpeg libsdl2-2.0-0
#
#    - name: Check SDL2
#      shell: bash
#      run: |
#        set -xeuo pipefail
#        rustc --version
#        cargo --version
#        
#    - name: Find dependencies paths
#      run: sudo find / -name libavutil.pc && sudo find / -name libavutil.a && sudo find / -name libSDL2.a
#
#    - name: Build
#      run : PKG_CONFIG_PATH="/home/ffmpeg" RUST_BACKTRACE=1 cargo build --verbose

#   build-macos:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v3
# 
#     - name: Install dependencies
#       run: |
#         curl -L -k -o SDL2-2.28.2.tar.gz "https://github.com/libsdl-org/SDL/releases/download/release-2.28.2/SDL2-devel-2.28.2-mingw.tar.gz"
#         tar -xvf SDL2-2.28.2.tar.gz
#         cp -r "/Users/runner/work/Pianorium/Pianorium/SDL2-2.28.2/x86_64-w64-mingw32/lib/" "/Users/runner/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/"
#         brew tap homebrew-ffmpeg/ffmpeg
#         brew install homebrew-ffmpeg/ffmpeg/ffmpeg \
#           --with-x264 \
#           --with-x265 \
# 
#       env: 
#         FFMPEG_DIR: /usr/local/Cellar/ffmpeg/6.0
# 
#     # DEBUG
#     # - name: Find dependencies paths
#     #   run: sudo find / -name libavutil.a & sudo find / -name libSDL2.a
# 
#     - name: Build
#       run: RUST_BACKTRACE=1 cargo build --verbose

  build-windows-msys:
    runs-on: windows-latest
    steps:
    - shell: pwsh
      run: git config --global core.autocrlf input
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-openssl
    
    - name: Update Msys deps
      shell: msys2 {0}
      run: |
        pacman -Syu

    - name: Install Msys deps
      shell: msys2 {0}
      run: |
        pacman -Syu
        y
        pacman -S make git diffutils nasm yasm pkgconf
        y

    - name: Install SDL2
      shell: pwsh
      run: |
        Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-2.28.2/SDL2-devel-2.28.2-mingw.zip" -OutFile SDL2-2.28.2.zip
        7z x SDL2-2.28.2.zip
        Copy-Item -Path "SDL2-2.28.2\x86_64-w64-mingw32\lib\*" -Destination "C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib" -Recurse
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        mkdir -p deps/source/x264 & mkdir -p deps/source/ffmpeg & mkdir -p deps/build/x264 & mkdir -p deps/build/ffmpeg & mkdir -p deps/installed
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\deps\installed`n"

    - name: Install x264 and FFmpeg
      shell: sh
      run: |
        git clone https://code.videolan.org/videolan/x264.git deps/source/x264
        curl "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD" > deps/source/x264/config.guess
        sed -i 's/host_os = mingw/host_os = msys/' deps/source/x264/configure
        CC=cl deps/source/x264/configure --prefix=deps/installed --enable-static
        make -j 2
        make install
        git clone https://git.ffmpeg.org/ffmpeg.git deps/source/ffmpeg
        CC=cl PKG_CONFIG_PATH=deps/installed/lib/pkgconfig deps/source/configure --prefix=deps/installed --toolchain=msvc --target-os=win64 --arch=x86_64 --enable-yasm --enable-asm --disable-shared --enable-static --enable-libx264 --enable-libx265 --enable-gpl --enable-version3 --disable-debug --enable-optimizations --extra-ldflags="-LIBPATH:deps/installed/lib" --extra-cxxflags="-Ideps/installed/include/ -MTd -Od -Zi" --extra-cflags="-Ideps/installed/include/ -MTd -Od -Zi"
        make -j 2
        make install

    # # DEBUG
    # - name: Find dependencies paths
    #   shell: cmd
    #   run: |
    #     cd D:\a\Pianorium\Pianorium
    #     dir /s avutil.lib & dir /s libSDL2.a & dir /s sdl2.pc

    - name: Build
      shell: sh
      run: RUST_BACKTRACE=1 cargo build --verbose