name: Pianorium

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs: # Add caching
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd /home
        sudo apt-get update -y -qq && sudo apt-get -y install ffmpeg libsdl2-2.0-0

    - name: Check SDL2
      shell: bash
      run: |
        set -xeuo pipefail
        rustc --version
        cargo --version
        
    - name: Find dependencies paths
      run: find / -name libavutil.pc && find / -name libavutil.a && find / -name libSDL2.a

    - name: Build
      run : PKG_CONFIG_PATH="/home/ffmpeg" RUST_BACKTRACE=1 cargo build --verbose

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install sdl2 ffmpeg pkg-config
        # Add-Content $env:GITHUB_ENV "FFMPEG_DIR=/usr/local/Cellar/ffmpeg/6.0"
        # Add-Content $env:GITHUB_PATH "/usr/local/Cellar/SDL2/2.28.2" #RUSTFLAGS

    # - name: Find dependencies paths
    #   run: sudo find / -name libavutil.pc && sudo find / -name libavutil.a && sudo find / -name libSDL2.a

    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        Invoke-WebRequest "https://libsdl.org/release/SDL2-2.28.2.zip" -OutFile SDL2-2.28.2.zip
        7z x SDL2-2.28.2.zip
        mkdir SDL2
        mv SDL2-*/* SDL2/
        cd SDL2
        ./configure
        make
        make install
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile ffmpeg-release-full-shared.7z
        7z x ffmpeg-release-full-shared.7z
        mkdir ffmpeg
        mv ffmpeg-*/* ffmpeg/
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        
    - name: Find dependencies paths
      shell: cmd
      run: |
        cd D:\
        dir /s libavutil.a && dir /s libSDL2.a
        cd D:\a\Pianorium\Pianorium

    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose