name: Pianorium

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - name: Install ffmpeg
      run: |
        mkdir tmp && mkdir tmp/installed && mkdir tmp/build && mkdir tmp/build/ffmpeg && mkdir tmp/sources && mkdir tmp/sources/ffmpeg
        cd tmp/sources
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ..
        CC=cl PKG_CONFIG_PATH=./installed/lib/pkgconfig ./sources/ffmpeg/configure --prefix=./installed --toolchain=msvc --target-os=win64 --arch=x86_64 --enable-yasm --enable-asm --disable-shared --enable-static --enable-libx264 --enable-gpl --disable-nonfree --enable-debug --extra-ldflags="-LIBPATH:./installed/lib" --extra-cxxflags="-I./installed/include/ -MTd -Od -Zi" --extra-cflags="-I./installed/include/ -MTd -Od -Zi"
        make -j 2
        make install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
