name: Pianorium

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs: # Add caching
  build-linux: # SDL2 works
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd /home
        mkdir -p ~/ffmpeg_sources ~/bin
        sudo apt-get update -y -qq && sudo apt-get -y install \
          autoconf \
          automake \
          build-essential \
          cmake \
          clang \
          ffmpeg \
          git-core \
          libass-dev \
          libfreetype6-dev \
          libgnutls28-dev \
          libmp3lame-dev \
          libnuma-dev \
          libsdl2-dev \
          libtool \
          libva-dev \
          libvdpau-dev \
          libvorbis-dev \
          libx264-dev \
          libx265-dev \
          libxcb1-dev \
          libxcb-shm0-dev \
          libxcb-xfixes0-dev \
          meson \
          nasm \
          ninja-build \
          pkg-config \
          texinfo \
          wget \
          yasm \
          zlib1g-dev
        sudo apt install libunistring-dev libaom-dev libdav1d-dev
        cd ~/ffmpeg_sources && \
        wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
        tar xjvf ffmpeg-snapshot.tar.bz2 && \
        cd ffmpeg && \
        PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
          --prefix="$HOME/ffmpeg_build" \
          --pkg-config-flags="--static" \
          --extra-cflags="-I$HOME/ffmpeg_build/include" \
          --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
          --extra-libs="-lpthread -lm" \
          --ld="g++" \
          --bindir="$HOME/bin" \
          --enable-gpl \
          --enable-libx264 && \
        PATH="$HOME/bin:$PATH" make -j 2 && \
        make install && \
        hash -r && \
        source ~/.profile

    - name: Check SDL2
      shell: bash
      run: |
        set -xeuo pipefail
        rustc --version
        cargo --version
        
    - name: Find dependencies paths
      run: sudo find / -name libavutil.a && sudo find / -name libSDL2.a

    - name: Build
      run : cargo build --verbose

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install sdl2 ffmpeg pkg-config
        # Add-Content $env:GITHUB_ENV "FFMPEG_DIR=/usr/local/Cellar/ffmpeg/6.0"
        # Add-Content $env:GITHUB_PATH "/usr/local/Cellar/SDL2/2.28.2" #RUSTFLAGS

    - name: Find dependencies paths
      run: find / -name libavutil.a && find / -name libSDL2.a

    - name: Build
      run: cargo build --verbose

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        Invoke-WebRequest "https://libsdl.org/release/SDL2-2.28.2.zip" -OutFile SDL2-2.28.2.zip
        7z x SDL2-2.28.2.zip
        mkdir SDL2
        mv SDL2-*/* SDL2/
        cd SDL2
        ./configure
        make
        make install
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile ffmpeg-release-full-shared.7z
        7z x ffmpeg-release-full-shared.7z
        mkdir ffmpeg
        mv ffmpeg-*/* ffmpeg/
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        
    - name: Find dependencies paths
      run: |
        cd D:\
        dir libavutil.a /s && dir libSDL2.a /s
        cd D:\a\Pianorium\Pianorium

    - name: Build
      run: cargo build --verbose